services:
  trino:
    env_file: "./trino.env"
    hostname: trino-coordinator
    ports:
      #- "9080:8080"
      - "8443:8443"
    image: "trinodb/trino:472"
    container_name: trino_coordinator
    networks:
     - network_test
    restart: unless-stopped
    volumes:
      - ./etc:/etc/trino
    extra_hosts:
        - "host.docker.internal:host-gateway"
        - "trino-worker:10.128.15.221"
networks:
  network_test:
    name: network_test
    external: true
